# Generated by Django 4.0.2 on 2022-03-11 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 11, 16, 19, 32, 251998), verbose_name='Date du commentaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('stockage', models.TextField()),
                ('valide', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.CharField(max_length=100)),
                ('reponse', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 11, 16, 19, 32, 251998), verbose_name='Date de la reponse')),
                ('id_commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ressources.commentaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favoris', models.BooleanField()),
                ('exploite', models.BooleanField()),
                ('sauvegarde', models.BooleanField()),
                ('id_citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.citoyen')),
                ('id_ressources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ressources.ressources')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commentaire',
            name='id_ressources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ressources.ressources'),
        ),
    ]
