# Generated by Django 4.0.2 on 2022-03-11 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 11, 16, 20, 11, 225681), verbose_name='Date du commentaire'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 11, 16, 20, 11, 226679), verbose_name='Date de la reponse'),
        ),
    ]
