# Generated by Django 4.0.3 on 2022-03-12 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0002_alter_commentaire_date_alter_reponse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='FromCom',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 12, 16, 12, 34, 95584), verbose_name='Date du commentaire'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 12, 16, 12, 34, 96585), verbose_name='Date de la reponse'),
        ),
    ]
