# Generated by Django 4.0.2 on 2022-03-08 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_alter_ressources_stockage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consule',
            new_name='Consulte',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 8, 18, 51, 41, 30349), verbose_name='Date du commentaire'),
        ),
        migrations.AddField(
            model_name='reponse',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 8, 18, 51, 41, 30349), verbose_name='Date de la reponse'),
        ),
    ]
