# Generated by Django 4.0.2 on 2022-03-13 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ressources', '0003_alter_consulte_exploite_alter_consulte_favoris_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulte',
            name='id_citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
