# Generated by Django 4.0.2 on 2022-03-10 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0003_rename_consule_consulte_commentaire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 16, 47, 26, 17470), verbose_name='Date du commentaire'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='id_ressources',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RSR.ressources'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 16, 47, 26, 17470), verbose_name='Date de la reponse'),
        ),
    ]
