# Generated by Django 4.0.3 on 2022-03-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0004_alter_consulte_id_citoyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressources',
            name='visits',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de visites'),
        ),
    ]
