# Generated by Django 4.0.3 on 2022-03-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0004_remove_citoyen_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
