# Generated by Django 4.0.3 on 2022-03-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('Ressources', '0005_alter_citoyen_date_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citoyen',
            name='user',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='consulte',
            name='id_citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.citoyen'),
        ),
        migrations.DeleteModel(
            name='Citoyen',
        ),
    ]
