# Generated by Django 4.0.3 on 2022-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0005_ressources_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressources',
            name='visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de visites'),
        ),
    ]
