# Generated by Django 4.0.3 on 2022-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0007_ressources_refus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressources',
            name='refus',
        ),
        migrations.AlterField(
            model_name='ressources',
            name='valide',
            field=models.IntegerField(default=1),
        ),
    ]
