# Generated by Django 4.0.3 on 2022-03-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0008_remove_ressources_refus_alter_ressources_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressources',
            name='titre',
            field=models.CharField(max_length=300),
        ),
    ]
