# Generated by Django 4.0.3 on 2022-03-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id_Citoyen', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('Mail', models.EmailField(max_length=75)),
                ('Actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_Com', models.BigAutoField(primary_key=True, serialize=False)),
                ('Auteur', models.CharField(max_length=100)),
                ('Date', models.DateField(verbose_name='Date de publication')),
                ('Commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_Groupe', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id_Ressources', models.BigAutoField(primary_key=True, serialize=False)),
                ('Titre', models.CharField(max_length=100)),
                ('Date_crea', models.DateField(verbose_name='Date de création')),
                ('Auteur', models.CharField(max_length=100)),
                ('Stockage', models.CharField(max_length=500)),
                ('Valide', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_Role', models.BigAutoField(primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id_Reponse', models.BigAutoField(primary_key=True, serialize=False)),
                ('Auteur', models.CharField(max_length=100)),
                ('Date', models.DateField(verbose_name='Date de réponse')),
                ('Reponse', models.TextField()),
                ('id_Commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Consule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favoris', models.BooleanField()),
                ('Exploite', models.BooleanField()),
                ('Sauvegarde', models.BooleanField()),
                ('id_Citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.citoyen')),
                ('id_Ressources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.ressources')),
            ],
        ),
        migrations.AddField(
            model_name='commentaire',
            name='id_Ressources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSR.ressources'),
        ),
    ]
