# Generated by Django 4.0.3 on 2022-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressources',
            name='stockage',
            field=models.TextField(),
        ),
    ]
